# Generated by Django 5.2.12 on 2026-04-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=100)),
                ('tema', models.TextField(blank=True)),
                ('fecha', models.DateTimeField()),
                ('recordatorio', models.BooleanField(default=True)),
                ('completada', models.BooleanField(default=False)),
                ('satisfaccion', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('planilla', '📊 Planilla'), ('documento', '📄 Documento'), ('actividad', '🎯 Actividad'), ('video', '🎬 Video'), ('enlace', '🔗 Enlace'), ('otro', '📦 Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('enlace', models.URLField(blank=True)),
                ('etiquetas', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('no_empezada', 'No empezada'), ('en_proceso', 'En proceso'), ('completada', 'Completada')], default='no_empezada', max_length=20)),
                ('plazo', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['plazo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('password_hash', models.CharField(max_length=200)),
                ('recibir_correos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaKleit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tema_original', models.CharField(max_length=200)),
                ('grupo_original', models.CharField(max_length=100)),
                ('expansion', models.TextField(blank=True)),
                ('guardada', models.BooleanField(default=False)),
                ('recursos_sugeridos', models.TextField(blank=True)),
                ('actividades_detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usada_en_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_kleit', to='kiwi.clase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionKleit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=100)),
                ('nivel_detectado', models.CharField(blank=True, max_length=50)),
                ('prompt_completo', models.TextField(blank=True)),
                ('respuesta_ia', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ideas', models.ManyToManyField(blank=True, to='kiwi.ideakleit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
