# Generated by Django 5.2.13 on 2026-05-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0002_clase_google_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plan_aula', 'Plan de Aula'), ('pensum', 'Pensum / Malla Curricular')], default='plan_aula', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('grado', models.CharField(choices=[('jardin', 'Jardín'), ('transicion', 'Transición'), ('primero', '1° Primaria'), ('segundo', '2° Primaria'), ('tercero', '3° Primaria'), ('cuarto', '4° Primaria'), ('quinto', '5° Primaria'), ('sexto', '6° Bachillerato'), ('septimo', '7° Bachillerato'), ('octavo', '8° Bachillerato'), ('noveno', '9° Bachillerato'), ('decimo', '10° Bachillerato'), ('once', '11° Bachillerato')], max_length=20)),
                ('metodologia', models.CharField(choices=[('casel', 'CASEL — Marco SEL'), ('yale_ruler', 'Yale RULER — Inteligencia Emocional'), ('seligman_perma', 'Seligman PERMA — Psicología Positiva'), ('kabat_zinn_mbsr', 'Kabat-Zinn MBSR — Mindfulness'), ('rosenberg_cnv', 'Rosenberg CNV — Comunicación No Violenta'), ('apa', 'APA — Lineamientos Psicológicos'), ('icbf', 'ICBF Colombia — Bienestar Familiar'), ('integrado', 'Enfoque Integrado (Multi-metodológico)')], max_length=30)),
                ('objetivo_general', models.TextField()),
                ('competencias', models.TextField(blank=True)),
                ('contenido_tematico', models.TextField(blank=True)),
                ('estrategias', models.TextField(blank=True)),
                ('evaluacion', models.TextField(blank=True)),
                ('recursos_didacticos', models.TextField(blank=True)),
                ('duracion_semanas', models.IntegerField(default=4)),
                ('contenido_ia', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='clase_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrencias', to='kiwi.clase'),
        ),
        migrations.AddField(
            model_name='clase',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_fin_recurrencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='frecuencia_semanas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='ciclo',
            field=models.CharField(choices=[('ciclo_inicial', 'Ciclo Inicial (Jardín y Transición)'), ('ciclo_uno', 'Ciclo 1 (1° y 2° Primaria)'), ('ciclo_dos', 'Ciclo 2 (3° a 5° Primaria)'), ('ciclo_tres', 'Ciclo 3 (6° a 8° Bachillerato)'), ('ciclo_cuatro', 'Ciclo 4 (9° a 11° Bachillerato)')], default='ciclo_uno', max_length=20),
        ),
        migrations.AlterField(
            model_name='clase',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('enlace', 'Enlace web'), ('planilla', 'Planilla'), ('actividad', 'Actividad'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
