# Generated by Django 5.2.13 on 2026-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0003_plandeaula_clase_clase_padre_clase_es_recurrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeaula',
            name='periodo',
            field=models.CharField(blank=True, choices=[('I', 'Período I'), ('II', 'Período II'), ('III', 'Período III'), ('IV', 'Período IV')], default='I', max_length=5),
        ),
        migrations.AlterField(
            model_name='plandeaula',
            name='competencias',
            field=models.CharField(blank=True, choices=[('autoconciencia', 'Autoconciencia — Reconocimiento emocional'), ('autogestion', 'Autogestión — Regulación emocional'), ('conciencia_social', 'Conciencia Social — Empatía y perspectiva'), ('habilidades_relacionales', 'Habilidades Relacionales — Comunicación y vínculos'), ('toma_decisiones', 'Toma de Decisiones Responsable'), ('bienestar_integral', 'Bienestar Integral — Enfoque holístico')], default='bienestar_integral', max_length=50),
        ),
        migrations.AlterField(
            model_name='plandeaula',
            name='metodologia',
            field=models.CharField(choices=[('integrado', 'Enfoque Integrado (Multi-metodológico)')], default='integrado', max_length=30),
        ),
    ]
