# Generated by Django 5.2.12 on 2026-05-18 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0004_plan_aula_periodo_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
        migrations.AddField(
            model_name='ideakleit',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
        migrations.AddField(
            model_name='plandeaula',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
        migrations.AddField(
            model_name='sesionkleit',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiwi.usuario'),
        ),
    ]
