# Generated by Django 5.2.13 on 2026-05-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0006_sesionkleit_chat_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionkleit',
            name='prompt_completo',
        ),
        migrations.RemoveField(
            model_name='sesionkleit',
            name='respuesta_ia',
        ),
    ]
