# Generated by Django 5.2.12 on 2026-05-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0007_remove_sesionkleit_prompt_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeaula',
            name='desempenios_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
