# Generated by Django 5.2.12 on 2026-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwi', '0008_plandeaula_desempenios_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
